# Generated by Django 4.2.11 on 2024-05-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0004_rename_officeparish_soselectedofficial_parish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soselectedofficial",
            name="commission_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="soselectedofficial",
            name="expiration_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
