# Generated by Django 4.2.11 on 2024-05-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LALookup', '0006_rename_commission_date_soselectedofficial_commissioned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soselectedofficial',
            old_name='commissioned_date',
            new_name='commissionedDate',
        ),
        migrations.RenameField(
            model_name='soselectedofficial',
            old_name='expiration_date',
            new_name='expirationDate',
        ),
        migrations.RenameField(
            model_name='soselectedofficial',
            old_name='office_level',
            new_name='officeLevel',
        ),
    ]
