# Generated by Django 4.2.11 on 2024-05-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LALookup', '0008_alter_legislator_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='officeURL',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
