# Generated by Django 5.1.6 on 2025-03-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0011_user_remove_legislator_active_api"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soselectedofficial",
            old_name="email",
            new_name="officeEmail",
        ),
        migrations.RemoveField(
            model_name="legislator",
            name="status",
        ),
        migrations.RemoveField(
            model_name="soselectedofficial",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.AddField(
            model_name="legislator",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="legislator",
            name="ethnicity",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="legislator",
            name="parish",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="fullname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="homePhone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="instagram",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="mobile",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="personalEmail",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="photoURL",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soselectedofficial",
            name="youtube",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ethnicity",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="parish",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="soselectedofficial",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="soselectedofficial",
            name="gender",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="soselectedofficial",
            name="party",
            field=models.CharField(blank="U", db_index=True, max_length=200, null=True),
        ),
    ]
