# Generated by Django 4.2.20 on 2025-05-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0012_rename_email_soselectedofficial_officeemail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legislator",
            old_name="homePhone",
            new_name="personalPhone",
        ),
        migrations.RenameField(
            model_name="soselectedofficial",
            old_name="homePhone",
            new_name="personalPhone",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="homePhone",
            new_name="personalPhone",
        ),
    ]
