# Generated by Django 4.2.20 on 2025-05-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0013_rename_homephone_legislator_personalphone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soselectedofficial",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
    ]
