# Generated by Django 4.2.20 on 2025-05-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0014_soselectedofficial_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="soselectedofficial",
            name="officeURL",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
    ]
