# Generated by Django 4.2.20 on 2025-05-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0018_request_addresstext_request_lat_request_lon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="addressText",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
