# Generated by Django 4.2.20 on 2025-05-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0019_alter_request_addresstext_alter_request_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="body_request",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="body_response",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=100, null=True)),
                ("response_code", models.PositiveSmallIntegerField()),
                ("method", models.CharField(max_length=10, null=True)),
                ("remote_address", models.CharField(max_length=20, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("addressText", models.TextField(blank=True, null=True)),
                ("referrer", models.TextField(null=True)),
                (
                    "legislator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="LALookup.legislator",
                    ),
                ),
                (
                    "official",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="LALookup.soselectedofficial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="LALookup.user",
                    ),
                ),
            ],
        ),
    ]
