# Generated by Django 4.2.20 on 2025-05-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0020_alter_request_body_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="request",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
