# Generated by Django 4.2.20 on 2025-05-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0022_request_user_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "campaign_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "campaign_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="cecaeb3292474f6aaf90914a4273929f",
                        max_length=40,
                    ),
                ),
                (
                    "allowed_referrer_domain",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("hit_count", models.IntegerField(db_index=True, default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LALookup.client",
                    ),
                ),
            ],
        ),
    ]
