# Generated by Django 4.2.20 on 2025-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0024_request_campaign_id_alter_campaign_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="be197ea7bf2e4a0f9810e93265959f4c",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="campaign_id",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
