# Generated by Django 4.2.20 on 2025-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0025_alter_campaign_campaign_id_alter_request_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="d221b2cd98db47ebb980b4149bf904f3",
                max_length=40,
            ),
        ),
        migrations.DeleteModel(
            name="Log",
        ),
    ]
