# Generated by Django 4.2.20 on 2025-05-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0026_alter_campaign_campaign_id_delete_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="campaign_id",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="71820116a00f4c549964f73929af6872",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="CampaignPrompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="LALookup.campaign",
                    ),
                ),
            ],
        ),
    ]
