# Generated by Django 4.2.20 on 2025-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0028_campaign_created_campaign_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignprompt",
            name="hit_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="7bd0797660b64e19878dd892cf7c2101",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
