# Generated by Django 4.2.20 on 2025-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0029_campaignprompt_hit_count_alter_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="a85d5aef63044559b36385221f8c298f",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
