# Generated by Django 4.2.20 on 2025-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0030_alter_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="22184d1d4f7644d6b7553b997cd5cbf8",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
