# Generated by Django 4.2.20 on 2025-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0031_alter_campaign_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="campaign_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="campaign",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="03262a75254a4111ab8e58cb3a0e03cd",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.DeleteModel(
            name="CampaignPrompt",
        ),
    ]
