# Generated by Django 4.2.20 on 2025-05-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "LALookup",
            "0032_rename_campaign_name_campaign_name_campaign_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="header",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="3e484e989aad45dbb61084069f3578ab",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
