# Generated by Django 4.2.20 on 2025-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0033_campaign_description_campaign_header_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="33f9a15bf9f045ce91eb487e297e0d22",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
