# Generated by Django 4.2.20 on 2025-05-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0034_alter_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="442c3b68bffc461d93cd1dea0a9349b8",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
