# Generated by Django 4.2.20 on 2025-06-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0035_alter_campaign_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="shared_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="4ceafccda8bd41cb80ad19607fbd088e",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
