# Generated by Django 4.2.20 on 2025-06-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0035_alter_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="58901acb712844ba96e711dc6125b1f7",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
