# Generated by Django 4.2.20 on 2025-06-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0036_campaign_shared_url_alter_campaign_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="72b83259523d492a9b62927dbaacdb59",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
