# Generated by Django 4.2.20 on 2025-06-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0036_alter_campaign_id"),
        ("LALookup", "0037_campaign_is_public_alter_campaign_id"),
    ]

    operations = []
