# Generated by Django 4.2.20 on 2025-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0038_merge_20250603_2237"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="03fb502c305b44b1ba2502158e166eb3",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
