# Generated by Django 4.2.20 on 2025-06-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0039_alter_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="bf6a710ada5847709052e391b9e52dd7",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
