# Generated by Django 4.2.20 on 2025-06-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LALookup", "0040_alter_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="28bedbdd89e845fb81fbbe1344546af4",
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
